import {Noto_Sans} from 'next/font/google'
import Header from './components/Header'
import "../sass/app.scss"
import logoLight from '../img/logo/logoLight.png'
export const metadata = {
  title: 'Raul Madero',
  description: 'Generated by create next app',
}
const noto = Noto_Sans({
  subsets: ['latin'],
  weight: ['400', '700']
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={noto.className}>
        <Header image={logoLight}/>
        {children}
      </body>
    </html>
  )
}
