import {Noto_Sans} from 'next/font/google'
import Header from './components/Header'
import Footer from './components/Footer'

import Script from 'next/script'
import "../sass/app.scss"
import logoLight from '../img/logo/logoLight.png'

const { initializeApp, applicationDefault, cert } = require('firebase-admin/app');
const { getFirestore, Timestamp, FieldValue, Filter } = require('firebase-admin/firestore');

initializeApp();

const db = getFirestore();

export const metadata = {
  title: 'Raul Madero',
  description: 'Generated by create next app',
}
const noto = Noto_Sans({
  subsets: ['latin'],
  weight: ['400', '700']
})



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={[noto.className, " bg-brown bg-opacity-50"]}>
        <Header image={logoLight}/>
        {children}
        <Footer image={logoLight}/>
      </body>
    </html>
  )
}
